const app = document.querySelector('#app');
const pageName = location.pathname.split('/').pop() || 'dashboard.php';
const pages = { 'dashboard.php': ['Admin Dashboard', 'dashboard'], 'index.php': ['Homepage Popup Control', 'popup'], 'slider.php': ['Hero Slider Manager', 'slider'], 'news.php': ['News Images Manager', 'news'], 'enquiries.php': ['Enquiries Database', 'enquiries'] };
const current = pages[pageName] || pages['dashboard.php'];
const esc = (v = '') => String(v).replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#039;', '"':'&quot;' }[c]));
const api = async (url, options = {}) => { const headers = options.body instanceof FormData ? {} : { 'Content-Type':'application/json' }; const response = await fetch(url, { credentials:'same-origin', ...options, headers:{ ...headers, ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || 'Request failed.'); return body; };
const notice = (message, error = false) => `<div class="alert ${error ? 'error' : 'success'}">${esc(message)}</div>`;
function login(error = '') {
  document.title = 'AIMS Popup Admin Login'; app.className = 'auth-card';
  app.innerHTML = `<div class="brand auth-brand"><div class="brand-mark">AIMS</div><div><p class="eyebrow">Secure Admin</p><h1>AIMS Popup Admin</h1></div></div><p class="hero-copy">Sign in to manage the homepage popup content, display timing, and popup image.</p>${error ? notice(error, true) : ''}<form id="login-form" autocomplete="off"><label>Username<input name="username" value="admin" required></label><label>Password<input type="password" name="password" required autofocus></label><button>Sign in</button></form>`;
  document.querySelector('#login-form').onsubmit = async event => { event.preventDefault(); const form = new FormData(event.currentTarget); if (form.get('username') !== 'admin') return login('Invalid username or password.'); try { await api('/backend/admin/api/login', { method:'POST', body:JSON.stringify({ password:form.get('password') }) }); location.href = '/backend/admin/dashboard.php'; } catch (reason) { login(reason.message); } };
}
function shell(content) {
  document.title = `${current[0]} | AIMS Admin`; const links = [['dashboard','Dashboard','dashboard.php'],['popup','Popup Manager','index.php'],['slider','Hero Slider','slider.php'],['news','News Images','news.php'],['enquiries','Enquiries','enquiries.php']]; app.className = 'admin-shell';
  app.innerHTML = `<aside class="sidebar"><a class="sidebar-brand" href="dashboard.php"><span>AIMS</span><strong>Campus Admin</strong></a><nav class="sidebar-nav">${links.map(([key,label,href]) => `<a class="${key === current[1] ? 'active' : ''}" href="${href}">${label}</a>`).join('')}</nav><div class="sidebar-note"><strong>Safe mode</strong><span>Only backend admin files and popup settings are editable now.</span></div></aside><section class="admin-main"><header class="admin-topbar"><div><p class="eyebrow">AIMS Campus Admin</p><h1>${current[0]}</h1></div><div class="hero-actions"><a class="ghost-link" href="/" target="_blank" rel="noreferrer">View Website</a><button class="logout" id="logout">Logout</button></div></header><div id="flash"></div>${content}</section>`;
  document.querySelector('#logout').onclick = async () => { await api('/backend/admin/api/logout', { method:'POST', body:'{}' }); location.href = '/backend/admin/login.php'; };
}
const flash = (message, error = false) => { const target = document.querySelector('#flash'); if (target) target.innerHTML = notice(message, error); };
const hero = (title, text) => `<section class="dashboard-hero compact"><div><p class="eyebrow">Connected Module</p><h2>${title}</h2><p>${text}</p></div><a class="ghost-link" href="dashboard.php">Back to Dashboard</a></section>`;
function dashboard() { shell(`<section class="module-grid">${[['📢','Popup Manager','Change popup text, button link, image, timing, and visibility.','index.php'],['📝','Hero Slider','Change the three homepage slider images safely from admin uploads.','slider.php'],['🖼️','News Images','Add new albums and images to News & Updates galleries.','news.php'],['📩','Enquiries Database','View contact form submissions saved securely in the backend MySQL database.','enquiries.php']].map(([icon,title,copy,href]) => `<article class="module-card ready"><div class="module-icon">${icon}</div><div><p class="eyebrow">Connected</p><h3>${title}</h3><p>${copy}</p><a href="${href}">Open module</a></div></article>`).join('')}</section>`); }
async function popup() {
  shell(`${hero('Popup Manager','Manage the admission popup message, display timing, button link, and image without touching the main website code.')}<section class="status-grid" id="popup-status"></section><section class="grid"><form class="panel" id="popup-form"><div class="panel-header"><div><p class="eyebrow">Settings</p><h2>Popup Content</h2></div><label class="switch"><input type="checkbox" name="enabled"><span></span>Display popup</label></div><div class="form-section"><h3>Display Rules</h3><div class="two"><label>Display frequency<select name="frequency"><option value="session">Once per browser session</option><option value="always">Every page load</option></select><small>Recommended: once per session, so visitors are not disturbed repeatedly.</small></label><label>Delay before display<input type="number" name="delayMs" min="0" max="10000"><small>Value is milliseconds. Example: 600 = 0.6 seconds.</small></label></div></div><div class="form-section"><h3>Text Content</h3><label>Small heading<input name="eyebrow" maxlength="40"></label><label>Main title<input name="title" maxlength="90"></label><label>Message<textarea name="message" maxlength="220"></textarea></label></div><div class="form-section"><h3>Buttons</h3><div class="two"><label>Main button label<input name="primaryLabel" maxlength="40"></label><label>Main button URL<input name="primaryUrl" maxlength="300"><small>Use website paths like /contact or safe https links.</small></label></div><label>Secondary button label<input name="secondaryLabel" maxlength="40"></label></div><div class="form-section"><h3>Image</h3><label>Image alt text<input name="imageAlt" maxlength="120"></label></div><div class="save-bar"><button>Save popup settings</button><span>Changes apply after saving and refreshing the website.</span></div></form><aside class="panel preview"><div class="panel-header"><div><p class="eyebrow">Live Preview</p><h2>Visitor View</h2></div><span class="preview-pill">Desktop</span></div><div class="phone-frame"><div class="popup-card" id="popup-preview"></div></div><form id="popup-image"><label class="upload-box">Replace popup image<input name="image" type="file" accept="image/jpeg,image/png,image/webp" required><small>JPG, PNG, or WEBP only. Maximum upload size is 2MB.</small></label><label>Image alt text<input name="imageAlt" maxlength="120"></label><button>Upload popup image</button></form></aside></section>`);
  const data = await api('/backend/admin/api/popup'); const form = document.querySelector('#popup-form'); for (const [key,value] of Object.entries(data)) if (form.elements[key]) form.elements[key].type === 'checkbox' ? form.elements[key].checked = Boolean(value) : form.elements[key].value = value || '';
  const refresh = value => { document.querySelector('#popup-status').innerHTML = [['Status',value.enabled?'Live':'Hidden'],['Frequency',value.frequency === 'always'?'Every Load':'Once Per Session'],['Delay',`${value.delayMs} ms`],['Image',value.imageUrl?'Custom':'Default']].map(([label,val]) => `<article class="status-card"><span>${label}</span><strong>${val}</strong></article>`).join(''); document.querySelector('#popup-preview').innerHTML = `${value.imageUrl ? `<img src="${esc(value.imageUrl)}" alt="">` : '<div class="placeholder">Using website default image until an admin image is uploaded.</div>'}<div class="popup-body"><p class="preview-eyebrow">${esc(value.eyebrow)}</p><h2>${esc(value.title)}</h2><p>${esc(value.message)}</p><div class="actions"><span>${esc(value.primaryLabel)}</span><span class="secondary">${esc(value.secondaryLabel)}</span></div></div>`; };
  refresh(data); form.onsubmit = async event => { event.preventDefault(); const value = Object.fromEntries(new FormData(form)); value.enabled = form.elements.enabled.checked; try { await api('/backend/admin/api/popup',{method:'PUT',body:JSON.stringify(value)}); refresh(value); flash('Popup settings saved successfully.'); } catch(reason) { flash(reason.message,true); } }; document.querySelector('#popup-image').onsubmit = async event => { event.preventDefault(); try { const result = await api('/backend/admin/api/popup/image',{method:'POST',body:new FormData(event.currentTarget)}); data.imageUrl=result.imageUrl; data.imageAlt=event.currentTarget.imageAlt.value; refresh(data); event.currentTarget.reset(); flash('Popup image updated successfully.'); } catch(reason) { flash(reason.message,true); } };
}
async function slider() {
  shell(`${hero('Homepage Slider Images','Upload replacement images for the three homepage hero slider positions. Text content stays unchanged for safety.')}<section class="grid"><form class="panel" id="slider-form"><div class="panel-header"><div><p class="eyebrow">Upload</p><h2>Replace Slider Image</h2></div></div><label>Choose slide<select name="index"><option value="0">Slide 1 - Main hero</option><option value="1">Slide 2 - UK recognised degrees</option><option value="2">Slide 3 - Admissions open</option></select></label><label class="upload-box">New slider image<input name="image" type="file" accept="image/jpeg,image/png,image/webp" required><small>Recommended wide image. JPG, PNG, or WEBP only. Maximum 2MB.</small></label><label>Image alt text<input name="imageAlt" maxlength="120" value="AIMS Campus homepage slider image"></label><div class="save-bar"><button>Save slider image</button><span>Refresh the website after saving.</span></div></form><aside class="panel"><div class="panel-header"><div><p class="eyebrow">Current Admin Images</p><h2>Uploaded Overrides</h2></div></div><div class="admin-image-list" id="slides"></div></aside></section>`);
  const render = async () => { const data=await api('/backend/api/slider.php'); const slides=data.slides||{}; document.querySelector('#slides').innerHTML=[0,1,2].map(index => {const item=slides[index]; return `<article><strong>Slide ${index+1}${index===0?' - Main hero':''}</strong>${item?.imageUrl?`<img src="${esc(item.imageUrl)}" alt=""><span>Custom image active</span>`:'<div class="placeholder small">Default website image active</div>'}</article>`;}).join('');}; await render(); document.querySelector('#slider-form').onsubmit=async event=>{event.preventDefault();try{await api('/backend/admin/api/slider',{method:'POST',body:new FormData(event.currentTarget)});event.currentTarget.reset();await render();flash('Slider image updated successfully.');}catch(reason){flash(reason.message,true);}};
}
async function news() {
  const existing={uel:'University of East London Partnership Highlights',orientation:'Student Orientation & Welcome Sessions',graduation:'Graduation Ceremony 2025','phd-evening':'PhD Evening','edex-edu':'EDEX Education Expo','aims-new-year':'AIMS New Year Festival 2024'}; shell(`${hero('News & Updates Gallery Uploads','Add new albums or upload images to News & Updates. Existing website images stay untouched.')}<section class="grid"><form class="panel" id="album-form"><div class="panel-header"><div><p class="eyebrow">Create</p><h2>Add New Album</h2></div></div><label>Album title<input name="title" maxlength="90" placeholder="Example: Open Day 2026" required></label><label>Category<input name="category" maxlength="40" placeholder="Example: Open Day" required></label><label>Album summary<textarea name="summary" maxlength="220" placeholder="Short description shown on the News & Updates page."></textarea></label><div class="save-bar"><button>Create album</button><span>Create the album first, then upload images to it.</span></div></form><form class="panel" id="news-form"><div class="panel-header"><div><p class="eyebrow">Upload</p><h2>Add News Image</h2></div></div><label>Choose album<select name="albumId" id="album-select"></select></label><label class="upload-box">New gallery image<input name="image" type="file" accept="image/jpeg,image/png,image/webp" required><small>JPG, PNG, or WEBP only. Maximum upload size is 2MB.</small></label><label>Image alt text<input name="alt" maxlength="140" value="AIMS Campus news gallery image"></label><div class="save-bar"><button>Add image to gallery</button><span>Images appear after refreshing News & Updates.</span></div></form></section><section class="panel wide-panel"><div class="panel-header"><div><p class="eyebrow">Uploaded</p><h2>Admin Gallery Albums</h2></div></div><div class="admin-image-list album-grid" id="albums"></div></section>`);
  const render=async()=>{const data=await api('/backend/api/news-images.php');const custom=data.customAlbums||{};const all={...existing,...Object.fromEntries(Object.entries(custom).map(([id,album])=>[id,album.title]))};document.querySelector('#album-select').innerHTML=Object.entries(all).map(([id,title])=>`<option value="${esc(id)}">${esc(title)}</option>`).join('');document.querySelector('#albums').innerHTML=Object.entries(all).map(([id,title])=>{const images=data.albums?.[id]||[];return `<article><strong>${esc(title)}</strong><span>${images.length} admin uploads${id.startsWith('admin-')?' · Custom album':''}</span>${images.length?`<div class="thumb-row">${images.slice(-3).map(image=>`<img src="${esc(image.src)}" alt="">`).join('')}</div>`:''}</article>`;}).join('');};await render();document.querySelector('#album-form').onsubmit=async event=>{event.preventDefault();try{const output=await api('/backend/admin/api/news/albums',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});event.currentTarget.reset();await render();document.querySelector('#album-select').value=output.id;flash('New album created successfully.');}catch(reason){flash(reason.message,true);}};document.querySelector('#news-form').onsubmit=async event=>{event.preventDefault();try{await api('/backend/admin/api/news/images',{method:'POST',body:new FormData(event.currentTarget)});event.currentTarget.reset();await render();flash('News image added successfully.');}catch(reason){flash(reason.message,true);}};
}
async function enquiries() {
  shell(`${hero('Contact Form Submissions','These enquiries are saved to the protected backend MySQL database.')}<section class="panel wide-panel"><div class="panel-header"><div><p class="eyebrow">Latest</p><h2 id="enquiry-count">Enquiries</h2></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Date</th><th>Name</th><th>Contact</th><th>Campus</th><th>Programme</th><th>Subject</th><th>Message</th><th>Status</th><th>Actions</th></tr></thead><tbody id="enquiry-list"></tbody></table></div><div class="save-bar"><span>Choose a status for any enquiry, then save all changes together.</span><button id="save-all-enquiries">Save all changes</button></div></section>`);
  const render=async()=>{const data=await api('/backend/admin/api/enquiries');document.querySelector('#enquiry-count').textContent=`${data.enquiries.length} enquiries`;document.querySelector('#enquiry-list').innerHTML=data.enquiries.length?data.enquiries.map(item=>`<tr data-id="${item.id}" data-original-status="${esc(item.status)}"><td>${esc(item.created_at)}</td><td>${esc(item.full_name)}</td><td><strong>${esc(item.phone)}</strong><span>${esc(item.email)}</span></td><td>${esc(item.campus)}</td><td>${esc(item.programme)}</td><td>${esc(item.subject)}</td><td>${esc(item.message)}</td><td><label>Status<select class="status"><option value="new" ${item.status==='new'?'selected':''}>New</option><option value="contacted" ${item.status==='contacted'?'selected':''}>Contacted</option><option value="closed" ${item.status==='closed'?'selected':''}>Closed</option></select></label></td><td><button class="delete">Delete</button></td></tr>`).join(''):'<tr><td colspan="9"><div class="empty-state">No enquiries saved yet.</div></td></tr>';};await render();document.querySelector('#save-all-enquiries').onclick=async()=>{const rows=[...document.querySelectorAll('#enquiry-list tr[data-id]')];try{await Promise.all(rows.filter(row=>row.querySelector('.status').value!==row.dataset.originalStatus).map(row=>api(`/backend/admin/api/enquiries/${row.dataset.id}`,{method:'PATCH',body:JSON.stringify({status:row.querySelector('.status').value})})));await render();flash('All enquiry status changes saved successfully.');}catch(reason){flash(reason.message,true);}};document.querySelector('#enquiry-list').onclick=async event=>{const row=event.target.closest('tr[data-id]');if(!row||!event.target.classList.contains('delete'))return;try{if(confirm('Permanently delete this enquiry? This cannot be undone.')){await api(`/backend/admin/api/enquiries/${row.dataset.id}`,{method:'DELETE',body:'{}'});await render();flash('Enquiry deleted permanently.');}}catch(reason){flash(reason.message,true);}};
}
(async()=>{try{const session=await api('/backend/admin/api/session');if(!session.authenticated)return login();({dashboard,popup,slider,news,enquiries})[current[1]]();}catch(reason){login(reason.message);}})();
